version: "3.8"
services:
  db:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: dev
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

  backend:
    container_name: backend
    build: ./backend
    depends_on:
      - db
    ports:
      - 3000:3000

  frontend:
    container_name: frontend 
    build: ./frontend
    ports:
      - 8080:80