# Offense count: 1
# Configuration parameters: IgnoredMethods, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 23

# Offense count: 3
# Configuration parameters: CountComments, CountAsOne, ExcludedMethods, IgnoredMethods.
Metrics/MethodLength:
  Max: 29

# Offense count: 2
# Configuration parameters: EnforcedStyle.
# SupportedStyles: slashes, arguments
Rails/FilePath:
  Exclude:
    - 'config/environments/development.rb'
    - 'spec/rails_helper.rb'




# Offense count: 15
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Exclude:
    - 'app/controllers/api/events_controller.rb'
    - 'app/controllers/api/messages_controller.rb'
    - 'app/controllers/api/teams_controller.rb'
    - 'app/controllers/api/users_controller.rb'
    - 'app/controllers/auth/registrations_controller.rb'
    - 'app/models/application_record.rb'
    - 'app/models/message.rb'
    - 'app/models/team.rb'
    - 'app/models/user.rb'
    - 'config/application.rb'
    - 'db/migrate/20220124215607_devise_token_auth_create_users.rb'
    - 'db/migrate/20220126110428_create_messages.rb'
    - 'db/migrate/20220204110024_create_events.rb'
    - 'db/migrate/20220214111725_create_teams.rb'
    - 'db/migrate/20220215001308_create_user_team_relationships.rb'

# Offense count: 50
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Offense count: 1
# This cop supports safe auto-correction (--auto-correct).
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/models/user.rb'

# Offense count: 2
# This cop supports safe auto-correction (--auto-correct).
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Layout/LineLength:
  Max: 154
