FROM ruby:3.0.3
WORKDIR /app
COPY ./ /app
RUN apt-get update -qq && bundle install
COPY entrypoint_dev.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint_dev.sh
# ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
# RUN chmod +x /wait
ENTRYPOINT ["entrypoint_dev.sh"]
