source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.3'

gem 'rails', '~> 6.1.4', '>= 6.1.4.4'
# gem 'bcrypt', '~> 3.1.7'
# gem 'vips', '~> 8.6', '>= 8.6.3.1'
gem 'aws-sdk-s3', '~> 1.2', require: false
gem 'image_processing', '~> 1.2'
gem 'mini_magick', '~> 4.5', '>= 4.5.1'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.4', require: false
# gem 'mysql2'

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'devise', '~> 4.8'
gem 'devise_token_auth', '~> 1.2'
gem 'faker', '~> 2.20'
gem 'mysql2'
gem 'omniauth', '~> 1.6', '>= 1.6.1'
gem 'puma', '~> 5.0'
gem 'rack-cors'

group :development, :test do
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'capybara', '~> 3.35'
  gem 'factory_bot_rails', '~> 6.0'
  gem 'rspec-rails', '~> 5.0'
  gem 'sqlite3', '~> 1.4'
end

group :development do
  gem 'listen', '~> 3.3'
  gem 'rename', '~> 1.0', '>= 1.0.8'
  gem 'rubocop-rails', '~> 2.14', '>= 2.14.2', require: false
  gem 'spring'
end

group :production do
  gem 'unicorn', '~> 6.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
